config/routes.rb
Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  root :to => 'user_sessions#new'

  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :articles do
    resources :article_versions
    put :edit_version
  end

  resources :agreements, param: :pid

  resources :groups do
    post :staff
  end

  resource :pending_agreements_report, only: [:show]
end

app/models/agreement.rb
class Agreement < ApplicationRecord
  belongs_to :staff
  belongs_to :article_version

  before_create do
    self.pid = SecureRandom.uuid
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_versions
  belongs_to :group, optional: true
  accepts_nested_attributes_for :article_versions
  scope :not_archived, -> { where("is_archived = false") }

  def latest_version
    article_versions.order(:id).reverse.first
  end
end

app/models/article_version.rb
class ArticleVersion < ApplicationRecord
  belongs_to :article
  has_one_attached :document
  has_many :agreements
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :staff_groups
  has_many :staffs, through: :staff_groups

  has_many :articles
end

app/models/staff.rb
class Staff < ApplicationRecord
  has_many :agreements
end

app/models/staff_group.rb
class StaffGroup < ApplicationRecord
  belongs_to :staff
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
end

app/controllers/agreements_controller.rb
class AgreementsController < ApplicationController
 skip_before_action :require_login, only: [:show, :update]

  def show

    @agreement = Agreement.find_by(pid: params[:pid])
    if  @agreement.article_version.article.is_archived
      render html: 'Document no longer exists.'
    end

    @agreements = @agreement.staff.agreements
  end

  def create
    emails = params[:emails].split(',')
    article_version = ArticleVersion.find(params[:av])
    agreements = []
    emails.each do |email|
      staff = Staff.find_or_create_by!(email:)
      agreements << Agreement.create!(staff:, article_version:)
    end

    agreements.flatten.each do |agreement| 
     StaffMailer.sop_email(agreement, true).deliver_now
    end

    redirect_back(fallback_location: article_path(id: article_version.article.id) )
  end

  def update
    @agreement = Agreement.find_by(pid: params[:pid])
    @agreement.agreed = true
    @agreement.agreed_at = Time.zone.now
    @agreement.save!
    redirect_back(fallback_location: agreement_path(pid: @agreement.pid) )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
end

app/controllers/article_versions_controller.rb
class ArticleVersionsController < ApplicationController
  def edit
    @article = Article.find(params[:id])
    @latest_version = @article.article_versions.order(created_at: :desc).first
    @form = ArticleVersions::CreateForm.new(article: @article)
  end

  def create
    @article = Article.find(params[:article_id])
    ready_params = article_params.merge(article: @article)
    @form = ArticleVersions::CreateForm.new(ready_params).save
    redirect_to articles_path
  end

  def article_params
    params.require(:article_versions_create_form).permit(:document, :pid, :notes)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.not_archived
    @pending_documents_count = Agreement.where(agreed: false).count
  end

  def show
    @article = Article.find(params[:id])
    @latest_version = @article.article_versions.order(created_at: :desc).first
  end

  def edit
    @article = Article.find(params[:id])
    @latest_version = @article.article_versions.order(created_at: :desc).first
  end

  def update
    @article = Article.find(params[:id])
    @group = Group.find(params[:article][:group_id])
    @article.update!(group: @group)

    @group.staffs.each do |staff|
      AddEmailsToArticle.new(emails: [staff.email], article: @article).call
    end

    redirect_to articles_path(@article)
  end

  def new
    @article = Article.new
    version = @article.article_versions.build
  end

  def create
    emails = params[:emails].split(',')
    agreements = []
    Article.transaction do
      params['files'].each_with_index do |file, index|
        article = Article.create!(title: params['file_names'][index.to_s])
        article_version = ArticleVersion.create!(pid: '1.0', document: file, article:)
        AddEmailsToArticle.new(emails:, article:).call
      end
    end

    redirect_to articles_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.is_archived = true
    @article.save
    redirect_to articles_path
  end


  def articles
    @group = Group.find(params[:group_id])
    article = Article.find(params[:article_id])
    @new_group_article = @group.article_groups.create!(article: article)

    AddEmailsToArticle.new(emails: @group.staffs.map(&:email), article:).call

    redirect_to group_path(@group)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @group = Group.new
    @groups = Group.all
  end

  def create
    Group.create!(title: params[:group][:title])
    redirect_to groups_path
  end

  def show
    @group = Group.find(params[:id])
    @staff = @group.staffs.all
    @new_group_staff = @group.staffs.build
  end

  def delete; end

  def staff
    @group = Group.find(params[:group_id])
    new_staff =  @group.staffs.create!(email: params[:staff][:email])


    @group.articles.each do |article|
      AddEmailsToArticle.new(emails: [new_staff.email], article:).call
    end

    redirect_to group_path(@group)
  end

end

app/controllers/pending_agreements_reports_controller.rb
class PendingAgreementsReportsController < ApplicationController
  def show
    @agreements = Agreement.where(agreed: false)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to(articles_path, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agreements/show.html.erb
<style>
</style>

<div style="display: flex; justify-content: space-between; margin-left: auto; margin-right: auto; max-width: 60rem">
  <div class="sidebar">
    <% @agreements.each do |agreement| %>
      <%= link_to agreement_path(pid: agreement.pid) do %>
        <li>
          <%= agreement.article_version.article.title %>
        </li>
      <% end %>
    <% end %>
  </div>

  <div class="content">
    <div class="content">
      Please agree to:
      <%= @agreement.article_version.article.title %>
    </div>


    <iframe src="<%= rails_blob_url(@agreement.article_version.document, disposition: :inline) %>" width="600" height="400" style="border:none;"></iframe>

    <div>
      <%= @agreement.article_version.pid %>
    </div>

    <div>
      <%= @agreement.article_version.notes %>
    </div>

    <% if !@agreement.agreed %>
      <%= form_with url: agreement_path, method: :put do |form| %>
        <%= form.submit 'I agree' %>
      <% end %>
    <% else %>
      You agreed to this on <%= @agreement.agreed_at %>.
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<%= link_to 'Back', article_path(@article) %>

<h1>
  <%= @article.title %>
</h1>

<%= @latest_version.pid %>

<%= form_with model: @form, url: article_article_versions_path(@article) do |form| %>
  <div>
    <h2>Version Changes</h2>
    <div class="field">
      <%= form.label :pid, "Version" %>
      <%= form.text_field :pid, id: :pid%>
    </div>


    <div class="field">
      <%= form.label :document, "Document" %>
      <%= form.file_field :document %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "Make Change" %>
  </div>
<% end %>

app/views/articles/index.html.erb
<h1>Documents</h1>

<div>
  <%= link_to "Groups", groups_path  %>
</div>

<% if @pending_documents_count > 0 %>
  <div>
    There is <%= link_to "#{@pending_documents_count} pending agreement(s).", pending_agreements_report_path %>
  </div>
<% end %>

<%= link_to "Add Document", new_article_path  %>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article_path(article) do %>
        <%= article.title %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/articles/new.html.erb
Create Article

<div data-controller="article-upload">
  <%= form_with url: articles_path, id: 'file-upload-form' do |form| %>
    <%= form.file_field :files, multiple: true, name: 'files[]', id: 'file-input', data: {article_upload_target: 'input'} %>
    <div data-article-upload-target="fileNamesContainer"></div>
    <div data-article-upload-target="staffContainer" style="display: none">
      <%= form.label 'List emails:' %>
      <%= form.text_field :emails %>
    </div>
    <%= form.submit %>
  <% end %>
</div>

app/views/articles/show.html.erb
<%= link_to 'Back', articles_path %>

<h1><%= @article.title %></h1>

<%= @latest_version.pid %>

<%= link_to "Add new Version", edit_article_article_version_path(@article) %>

<%= button_to 'Archive', article_path, method: :delete %>

<% if @latest_version.document.attached? %>
  <iframe src="<%= rails_blob_url(@latest_version.document, disposition: :inline) %>" width="600" height="400" style="border:none;"></iframe>
<% end %>

<h3>Staff</h3>
<ul>
  <% @latest_version.agreements.each do |agreement| %>
    <li><%= agreement.staff.email %> - Agreed? <%= agreement.agreed %></li>
  <% end %>
</ul>

<%= form_with url: agreements_path(av: @latest_version.id) do |form| %>
  <div>
    <%= form.label 'Add emails:' %>
    <%= form.text_field :emails %>
  </div>
  <%= form.submit 'Add' %>
<% end %>

<%= form_with model: @article, url: article_path(@article), method: :put do |form| %>
  <%= form.label 'Select Group:' %>
  <%= form.collection_select :group_id, Group.all, :id, :title, {prompt: 'Please Select' }  %>
  <%= form.submit 'Save' %>
<% end %>

app/views/groups/index.html.erb
<%= link_to 'Back', articles_path %>
<h1>Groups</h1>

<%= form_with model: @group, url: groups_path do |form| %>
  <%= form.label 'Group name:' %>
  <%= form.text_field :title %>

  <%= form.submit 'Create' %>
<% end %>

<ul>
  <% @groups.each do |group| %>
    <li><%= link_to group.title, group_path(group) %>
    </li>
  <% end %>
</ul>

app/views/groups/show.html.erb
<%= link_to 'Back', groups_path %>

<h1>
  <%= @group.title %>
</h1>


<%= form_with model: @new_group_staff, url: group_staff_path(group_id: @group.id) do |form| %>
  <%= form.label 'Email:' %>
  <%= form.email_field :email %>

  <%= form.submit 'Add' %>
<% end %>


<ul>
  <% @staff.each do |staff| %>
    <li><%= staff.email %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sopstash</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pending_agreements_reports/show.html.erb
<%= link_to 'Back', articles_path %>

<h1>Pending Agreements</h1>

<ul>
  <% @agreements.each do |agreement| %>
    <li>
      <%= agreement.staff.email %> - <%= agreement.article_version.article.title %> - Sent at: <%= agreement.created_at %>
    </li>
  <% end %>
</ul>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= form_with url: login_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Login" %>
  </div>
<% end %>